### ISSUE TITLE
Message couldn't be successfully sent. Reason: invalid_auth

### ISSUE THREAD

**Issue by evanccnyc** [Graylog2/graylog-plugin-slack#11]
Hey there,

I am using 1.1.6 installed via a deb file and no matter what I always receive "Message couldn't be successfully sent. Reason: invalid_auth".

I know my token is right because I tested it with ansible and it sent the message properly.  Any idea whats going on here?

**Comment by joschi** [comment]
Please create another token as described at https://github.com/Graylog2/graylog-plugin-slack#usage and try again.

If something went wrong, you should find details about the error in the logs of your Graylog server node (search for `SlackClient`).

**Comment by evanccnyc** [comment]
That worked. Thanks and sorry for the spam.
