### ISSUE TITLE
Private channel Support

### ISSUE THREAD

**Issue by AndyWTBlueHair** [Graylog2/graylog-plugin-slack#16]
The plugin will 500 when attempting to use a private channel with an error requiring either # or @

This is likely fixed in the SlackPluginBase.java around line 96 to simply remove the requirement, but my java is not good enough to pretend like I know for sure how it'll all tie together.

**Comment by joschi** [comment]
@AndyWTBlueHair Please try out the latest version of this plugin.

I'll close this issue, but feel free to add a comment if the problem still exists.
