### ISSUE TITLE
Getting 500 Error

### ISSUE THREAD

**Issue by phlegx** [Graylog2/graylog-plugin-slack#24]
Hi, 

I'm trying out the newest version of the graylog slack plugin (`graylog-plugin-slack-2.2.1.jar`) but I do get the following error:

`Could not send message to Slack.`

Digging into the logs I do get:

`Caused by: org.graylog2.plugins.slack.SlackClient$SlackClientException: Unexpected HTTP response status 500`

Not sure what is causing that. The Webhook URL is correct, I even used another Webhook URL that used to work, but I'm getting the same error. I also tried with the older plugin, but I get the same problem. Here is what Slack says about 500 Errors: https://api.slack.com/changelog/2016-05-17-changes-to-errors-for-incoming-webhooks

Any ideas what might causing that?

PS: I add also my configuration of the plugin  within graylog:

```
        add_attachment:
         true
        channel:
         #log
        color:
         #FF0000
        graylog2_url:
         <empty>
        icon_emoji:
         <empty>
        icon_url:
         <empty>
        link_names:
         true
        notify_channel:
         false
        short_mode:
         false
        user_name:
         Graylog
        webhook_url:
         https://hooks.slack.com/services/T04AYXXX/B1G99JBS4/VRTK7x8r11xoLZBzXXXXXX
```

**Comment by jinmingshao** [comment]
I saw same error when slack disabled my webhook due to rate limit.

**Comment by phlegx** [comment]
OK yes that could be a cause. In the slack dashboard it states that I'm "approaching the limits",. But there is no erro or warning that I would already have reached it.

Also: wouldn't' then the older webhook simply work? Since I tried the older webhook (which I use for deployment notifications) and it didn't work with that either...

**Comment by phlegx** [comment]
Hmm but Slack states;

```
If you go over these limits when using our HTTP based APIs, including Incoming Webhooks, Slack will start returning a HTTP 429 Too Many Requests error, a JSON object containing the number of calls you have been making, and a Retry-After header containing the number of seconds until you can retry.
```
See: https://api.slack.com/docs/rate-limits

**Comment by joschi** [comment]
While I couldn't reproduce the described problem, I've added a more verbose logging (including the actual HTTP response body) in case of an unsuccessful request.
