### ISSUE TITLE
Only a small amount of information shows up in slack message

### ISSUE THREAD

**Issue by joemsanchez** [Graylog2/graylog-plugin-slack#25]
I had to rebuild this graylog box.  I've gotten everything back up, except getting the full windows event info in a slack message.  I looked back through my slack history, and I see the older messages which basically dumped the entire event detail in the message.  I've gone over my slack settings and I made sure Include more information(optional) is checked on manage outputs and manage alerts.  Its been awhile since I had configured slack for graylog, but I don't remember having to do anything special to get the full event message.  I know there is an option to shorten the message, I made sure that was unchecked.

**Comment by joemsanchez** [comment]
I apologize I worked on this for a while yesterday, and no luck.  Come into work this morning, and there were a few alerts with the full event detail.  You can just go ahead and delete this as I hang my head in shame.

**Comment by dennisoelkers** [comment]
@joemsanchez, cut yourself some slack! :) Thank you for using Graylog and getting in touch with us.
