### ISSUE TITLE
rocketchat compatibility 

### ISSUE THREAD

**Issue by JakeDEvans** [Graylog2/graylog-plugin-slack#28]
When setting up this hook for rocketchat (uses the slack/mm api) my body is always empty.

Additional info:
https://github.com/RocketChat/Rocket.Chat/issues/2725

**Comment by joschi** [comment]
@JakeDEvans We currently won't invest too much time into making this plugin compatible to RocketChat.

This being said, a pull request to make this plugin compatible with Slack, Mattermost, and RocketChat would be certainly welcome.

**Comment by jothoma1** [comment]
I'm interested in this rocketchat compatibility too :+1:  :)

**Comment by LeDistordu** [comment]
+1

**Comment by navrocky** [comment]
+1

**Comment by joschi** [comment]
Sorry, but we don't have the bandwidth to address this problem right now.

It’s definitely a problem, and if someone can provide a fix for it we’ll work with them to get it merged, but none of the regular contributors are going to be able to get to this any time soon.

**Comment by MrDragon** [comment]
I'm running rocketchat 0.51.0 and it appears to work well. I don't have scripts enabled on the rocketchat web hook.
The only minor thing I had was that my graylog server log had these warnings:
`WARN  [SlackClient] Message couldn't be successfully sent. Response was: {"success":true}`

I fixed that by recompiling the source after making this change to  "SlackClient.java", line 82:
`if (response.equals("ok") || response.equals("{\"success\":true}")) {`
which is probably horrible, but I don't code in java/json and it works.

**Comment by JakeDEvans** [comment]
Worked for me!

**Comment by jothoma1** [comment]
@JakeDEvans Can you give your configuration? options of the slack plugin into graylog ? i always have errors...

**Comment by JakeDEvans** [comment]
![image](https://cloud.githubusercontent.com/assets/5014348/23035438/12f9ccca-f44d-11e6-95e0-8b5a020e01cb.png)

`Graylog 2.1.2+50e449a `

Running latest version of the plugin.

**Comment by navya-uppalapati** [comment]
Hi,
I want to send the graylog messages to rocketchat. I have configured the graylog in the similar way with slack plugin but it says "cannot send message to slack". what could be the error?
does rocket chat need to have a secure ssl connection? 
Graylog version - 2.3
Rocket chat - 0.57.2

I tried sending it slack to figured out and messages are successfully sent to slack.
Waiting for your response :)

**Comment by joschi** [comment]
@navrocky What's in the logs of your Graylog node when trying to send a message to Rocket.Chat?

**Comment by navya-uppalapati** [comment]
Thank you for responding :) 
It is like this ..

ERROR [OutputBufferProcessor] Error in output [class org.graylog2.plugins.slack.output.SlackMessageOutput].
java.lang.RuntimeException: Could not send message to Slack.
        at org.graylog2.plugins.slack.output.SlackMessageOutput.write(SlackMessageOutput.java:91) ~[?:?]
        at org.graylog2.buffers.processors.OutputBufferProcessor$1.run(OutputBufferProcessor.java:191) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.graylog2.plugins.slack.SlackClient$SlackClientException: Unexpected HTTP response status 404
        at org.graylog2.plugins.slack.SlackClient.send(SlackClient.java:72) ~[?:?]
        at org.graylog2.plugins.slack.output.SlackMessageOutput.write(SlackMessageOutput.java:89) ~[?:?]

**Comment by joschi** [comment]
@navrocky 
> Unexpected HTTP response status 404

Make sure that the URL in your plugin configuration is correct.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by phlegx** [comment]
Looks like newest version `3.0.1` does not send the additional lines anymore to Rocketchat. Also the stream link is not correct. 

Would be nice if RocketChat could be officially supported!
