### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by pauldsmyth** [Graylog2/graylog-plugin-slack#31]
Any chance of some proper build instructions rather than just expecting me to go off and read the entire maven documentation to figure out what to do with this code?

**Comment by dennisoelkers** [comment]
Build steps are explained here: https://github.com/Graylog2/graylog-plugin-slack#build - if you don't want to build it on your own, you can also just download a release.

**Comment by pauldsmyth** [comment]
Those instructions look dangerously like I'm going to write something to a repository: 
"This sets the version numbers, creates a tag and pushes to GitHub. TravisCI will build the release artifacts and upload to GitHub automatically."

What release? All I see is a src directory?

**Comment by jalogisch** [comment]
![graylog2_graylog-plugin-slack__graylog_alarm_callback_for_slack](https://cloud.githubusercontent.com/assets/404238/18706169/33db6b36-7ff1-11e6-9aa7-006693dbef60.png)

**Comment by dennisoelkers** [comment]
It says: `You can build a plugin (JAR) with mvn package.` - What more information do you need?
