### ISSUE TITLE
Not able to send alerts to slack

### ISSUE THREAD

**Issue by egobude** [Graylog2/graylog-plugin-slack#33]
Hey, 
 
when in try to send a test message i get the following error message from graylog:

Graylog-Version: Graylog 2.1.1+01d50e5
Slack Plugin Version: 2.2.1:

Any idea what causes the error? Thanks for your help :)

`
Caused by: org.graylog2.plugins.slack.SlackClient$SlackClientException: Unexpected HTTP response status 404
9.11.2016 14:23:13	at org.graylog2.plugins.slack.SlackClient.send(SlackClient.java:49) ~[?:?]
9.11.2016 14:23:13	at org.graylog2.plugins.slack.callback.SlackAlarmCallback.call(SlackAlarmCallback.java:56) ~[?:?]
9.11.2016 14:23:13	... 28 more
9.11.2016 14:23:432016-11-09 13:23:43,487 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
9.11.2016 14:23:43java.lang.RuntimeException: Could not send message to Slack.
9.11.2016 14:23:43	at org.graylog2.plugins.slack.callback.SlackAlarmCallback.call(SlackAlarmCallback.java:58) ~[?:?]
9.11.2016 14:23:43	at org.graylog2.rest.resources.streams.alerts.StreamAlertResource.sendDummyAlert(StreamAlertResource.java:313) ~[graylog.jar:?]
9.11.2016 14:23:43	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
9.11.2016 14:23:43	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
9.11.2016 14:23:43	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
9.11.2016 14:23:43	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
9.11.2016 14:23:43	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:143) ~[graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
9.11.2016 14:23:43	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
9.11.2016 14:23:43	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
9.11.2016 14:23:43	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
9.11.2016 14:23:43	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
9.11.2016 14:23:43	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
`

**Comment by joschi** [comment]
@egobude 
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
