### ISSUE TITLE
Installation fails for Graylog 2.2.2

### ISSUE THREAD

**Issue by NewEvolution** [Graylog2/graylog-plugin-slack#40]
Attempted to install the plugin into Graylog 2.2.2.  Copied the .jar into the plugin directory and restarted but the plugin does not appear on the System/Configurations page in the Plugins section.

**Comment by joschi** [comment]
@NewEvolution Which version of the plugin did you download?
Where exactly did you copy the JAR file?
What's the `journal_dir` setting in your Graylog installation?

**Comment by NewEvolution** [comment]
Downloaded graylog-plugin-slack-2.4.0.jar
JAR was copied to `/usr/share/graylog-server/plugin`
Setting in the running `server.conf` is `plugin_dir = /usr/share/graylog-server/plugin`

**Comment by NewEvolution** [comment]
Welp, figured it out when going back through the steps and noticing the jar was smaller than expected.

Used `curl` to pull the jar down directly on my Graylog server, actually just pulled down the "You are being redirected" page. 😬 

Pulled down the jar via browser and scp'd it over, installed and working properly. 👍

**Comment by joschi** [comment]
> Used `curl` to pull the jar down directly on my Graylog server, actually just pulled down the "You are being redirected" page. 😬 

FWIW, you can use curl's `-L` (`--location`) parameter to follow redirects.
