### ISSUE TITLE
Wrong plugin directory location for .deb

### ISSUE THREAD

**Issue by favadi** [Graylog2/graylog-plugin-slack#6]
graylag-server plugin directory is located at `/usr/share/graylog-server/plugin` but [graylog-plugin-slack .deb package](https://github.com/Graylog2/graylog-plugin-slack/releases/download/1.1.5/graylog-plugin-slack-1.1.5.deb) installed the .jar file at `/usr/share/graylog2-server/plugin/graylog-plugin-slack-1.1.5.jar`. Therefore, slack alarm callback doesn't show up in grayling web interface.

**Comment by bernd** [comment]
Thank you for the report!
