### ISSUE TITLE
Stream should be linked

### ISSUE THREAD

**Issue by bclermont** [Graylog2/graylog-plugin-slack#7]
If a stream alert ends in slack, for users to go back to Graylog and browse it, they need to note the ID, logs into Graylog and figure what is the stream and look at it.

<img width="328" alt="screen shot 2015-10-12 at 12 05 19" src="https://cloud.githubusercontent.com/assets/474302/10421362/9356ae22-70d9-11e5-9821-5118439acf8f.png">

Can stream ID be an ``<a>`` back to it?

**Comment by lennartkoopmann** [comment]
Thank you! Done a little bit differently (Linked stream title in headline) in 883300da7fa6935d0628412b2b63f88bc6a818db. Will be released soon.
