### ISSUE TITLE
Feature Request: Color

### ISSUE THREAD

**Issue by verschoof** [Graylog2/graylog-plugin-slack#8]
Hi,

I send an alert with slack and I would like to determine the color by my self, now I see a green border while its a critical error.

https://api.slack.com/docs/attachments (scroll down to **Color**)

I would like to make a PR but unfortunately I'm not known with Java.
So I would like to have a possibility to get a new field: Color

**Comment by lennartkoopmann** [comment]
Thank you! Scheduled for v1.2
